Feat 41 Catalogação Total Mensal
nikoz84/plataforma-anisio-teixeira pull request #64
Opened 2022-11-17 18:46 UTC by alexandreleao

- Input data inicio e data fim.
 - Filtro
 - Query Builder

2022-11-18 18:33 UTC, nikoz84 requested changes

2022-11-18 18:33 UTC, nikoz84 commented on resources/assets/js/components/dashboard/AplicativosMaisVisualizados.vue
> -        console.log(this.disableTable)
Remova o console.log

2022-11-18 18:33 UTC, nikoz84 commented on resources/assets/js/components/dashboard/CatalogacaoMensalPorUsuario.vue
> -        console.log(this.disableTable)
Remova o console.log

2022-11-18 18:33 UTC, nikoz84 commented on resources/assets/js/components/dashboard/CatalogacaoMensalPorUsuario.vue
> +            // console.log('oisio')
Mesma coisa

2022-11-18 18:33 UTC, nikoz84 commented on resources/assets/js/components/dashboard/CatalogacaoPorCanal.vue
> -        console.log(this.disableTable)
remover console.log

2022-11-18 18:33 UTC, nikoz84 commented on resources/assets/js/components/dashboard/CatalogacaoTotalMensal.vue
> -        console.log(this.disableTable)
remover console

2022-11-29 20:42 UTC, reinaldoweb commented
Conflitos resolvidos

2022-11-30 14:04 UTC, reinaldoweb commented
conflitos resolvidos

2022-11-30 14:04 UTC, merged